# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f32581d6d06c49d4a5b8d8625526b467976a7e5bfde597d8df2317efcf1b51a6cfa12c860173dfb39d985a96805067beb9919753683c2d37bcfdcd85ed017af4

test:
  secret_key_base: aa30406de4b16b291c1fea105c7188ad4e1622b22416ee2bf17fc9fb720d2ee6b3126440498c28175b1394abb53969010a247827c80aafb6dd4b7de3c9c8070e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
